// <auto-generated />
using System;
using FinalProject_Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject_Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240401064756_add-meeting-attendee-tables")]
    partial class addmeetingattendeetables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject_Data.Model.Attendee", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("meeting_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("attendees");
                });

            modelBuilder.Entity("FinalProject_Data.Model.Attendee_Meeting", b =>
                {
                    b.Property<string>("attendee_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("meeting_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("attendee_id", "meeting_id");

                    b.HasIndex("meeting_id");

                    b.ToTable("attendee_meetings");
                });

            modelBuilder.Entity("FinalProject_Data.Model.Attendee_MeetingForm", b =>
                {
                    b.Property<string>("attendee_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("meetingform_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("attendee_id", "meetingform_id");

                    b.HasIndex("meetingform_id");

                    b.ToTable("attendee_meetingforms");
                });

            modelBuilder.Entity("FinalProject_Data.Model.Meeting", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<string>("meeting_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("meeting_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("meetingform_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("meetingtime_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("platform")
                        .HasColumnType("int");

                    b.Property<DateTime>("starttime")
                        .HasColumnType("datetime2");

                    b.Property<int>("trangthai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("meetingform_id")
                        .IsUnique();

                    b.ToTable("meetings");
                });

            modelBuilder.Entity("FinalProject_Data.Model.MeetingForm", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<string>("meeting_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("meeting_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("meeting_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("platform")
                        .HasColumnType("int");

                    b.Property<DateTime>("starttime")
                        .HasColumnType("datetime2");

                    b.Property<int>("trangthai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("meetingforms");
                });

            modelBuilder.Entity("FinalProject_Data.Model.MeetingTime", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<string>("meetingID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("meetingform_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("meetingtime_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.Property<int>("trangthai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("meetingID");

                    b.HasIndex("meetingform_id");

                    b.ToTable("meetingtimes");
                });

            modelBuilder.Entity("FinalProject_Data.Model.Attendee_Meeting", b =>
                {
                    b.HasOne("FinalProject_Data.Model.Attendee", "attendee")
                        .WithMany()
                        .HasForeignKey("attendee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_Data.Model.Meeting", "meeting")
                        .WithMany("attendee_meetings")
                        .HasForeignKey("meeting_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("attendee");

                    b.Navigation("meeting");
                });

            modelBuilder.Entity("FinalProject_Data.Model.Attendee_MeetingForm", b =>
                {
                    b.HasOne("FinalProject_Data.Model.Attendee", "attendee")
                        .WithMany()
                        .HasForeignKey("attendee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_Data.Model.MeetingForm", "meetingform")
                        .WithMany("attendee_meetingforms")
                        .HasForeignKey("meetingform_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("attendee");

                    b.Navigation("meetingform");
                });

            modelBuilder.Entity("FinalProject_Data.Model.Meeting", b =>
                {
                    b.HasOne("FinalProject_Data.Model.MeetingForm", "meetingform")
                        .WithOne("meeting")
                        .HasForeignKey("FinalProject_Data.Model.Meeting", "meetingform_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("meetingform");
                });

            modelBuilder.Entity("FinalProject_Data.Model.MeetingTime", b =>
                {
                    b.HasOne("FinalProject_Data.Model.Meeting", "meeting")
                        .WithMany()
                        .HasForeignKey("meetingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_Data.Model.MeetingForm", "meetingform")
                        .WithMany("times")
                        .HasForeignKey("meetingform_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("meeting");

                    b.Navigation("meetingform");
                });

            modelBuilder.Entity("FinalProject_Data.Model.Meeting", b =>
                {
                    b.Navigation("attendee_meetings");
                });

            modelBuilder.Entity("FinalProject_Data.Model.MeetingForm", b =>
                {
                    b.Navigation("attendee_meetingforms");

                    b.Navigation("meeting")
                        .IsRequired();

                    b.Navigation("times");
                });
#pragma warning restore 612, 618
        }
    }
}
